### ISSUE TITLE
GUI Not Loading

### ISSUE THREAD

**Issue by PuruSinghvi** [atredispartners/aidapal#1]
The plugin stops working after the last output:

> aiDAPal: extra juice None

I am using IDA PRO 8.3 with Python 3.11

**Comment by AverageBusinessUser** [comment]
Greetings, 

Can you run the following to ensure you have the model setup and service running:

```
echo 'unsigned int sub_1234(int a1){return a1 ^ 0xff;}'|ollama run aidapal
```

This should return a JSON result like the following:

```json
{
  "function_name": "toggleBits",
  "comment": "This function takes an integer as input, XORs it with the binary value of 0xff (which is all 1's in binary), and returns the result.",
  "variables": [
    {
      "original_name": "a1",
      "new_name": "input"
    }
  ]
}
```

Thanks!

**Comment by onhexgroup** [comment]
> The plugin stops working after the last output:
> 
> > aiDAPal: extra juice None
> 
> I am using IDA PRO 8.3 with Python 3.11

I'm also using this config. The solution is to give it a little more time, say a few minutes.

**Comment by AverageBusinessUser** [comment]
> > The plugin stops working after the last output:
> > > aiDAPal: extra juice None
> > 
> > 
> > I am using IDA PRO 8.3 with Python 3.11
> 
> I'm also using this config. The solution is to give it a little more time, say a few minutes.

Thanks for the input - unfortunately the speed of response is going to be directly tied to your system, I've only done testing using mbp m1/m3 and nvidia 3090. I think if you follow any guides for running mistral7b on specific hardware there may be room for improvement - I'll be looking at some of the newer/smaller models soon.

**Comment by PuruSinghvi** [comment]
The issue was the python version, I had multiple Python installed and running idapythonswitch.exe to choose the correct one fixed it for me!
