### ISSUE TITLE
Installation not work

### ISSUE THREAD

**Issue by Bizarrus** [atredispartners/aidapal#4]
Tried in `IDA Pro 8.3` and `IDA Pro 9.0`.

## Reproduce
- Download / Clone this Repo
- Unzip / Move the Plugin to `C:\Program Files\IDA Professional 9.0\plugins\`
- Start `IDA`
- 

![image](https://github.com/user-attachments/assets/69e6b93f-3fe4-493f-a800-9a2189a30479)

On `Plugins`-List the plugin wont be listen:

![image](https://github.com/user-attachments/assets/3a7c7a0f-d416-44da-817c-2075007d62c2)

No Error logs, no exceptions, nothing..

## Solution
The `ida-plugin.json` is missing?

**Comment by Bizarrus** [comment]
See #5

**Comment by AverageBusinessUser** [comment]
merged the plugin json in, closing as fixed.
